# This file configures the cloudads application frontend. The frontend serves
# public web traffic.

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cloudads-frontend
  labels:
    app: cloudads
# The cloudads frontend replica set ensures that at least 3
# instances of the cloudads app are running on the cluster.
# For more info about Pods see:
#   https://cloud.google.com/container-engine/docs/pods/
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: cloudads
        tier: frontend
    spec:
      containers:
      - name: cloudads-app
        # Replace $GCLOUD_PROJECT with your project ID or use `make template`.
        image: gcr.io/tracker-198913/cloudads
        # This setting makes nodes pull the docker image every time before
        # starting the pod. This is useful when debugging, but should be turned
        # off in production.
        imagePullPolicy: Always
        # The cloudads process listens on port 8080 for web traffic by default.
        ports:
        - name: http-server
          containerPort: 8080
